In [11]:
import os, sys

sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient


class SimpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)  # 정규분포로 초기화

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss
    
net = SimpleNet()
print(net.W)

x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

print(np.argmax(p))

t = np.array([0,0,1]) # 정답 레이블
print(net.loss(x, t))

f = lambda w: net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.33992931  0.85136759 -0.62004287]
 [ 0.70572604 -1.33997541 -1.08211693]]
[ 0.83911102 -0.69515731 -1.34593096]
0
2.46878109248
[[ 0.45177784  0.09740935 -0.54918719]
 [ 0.67766675  0.14611403 -0.82378078]]
